ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1001
ARG PGID=1001
#
RUN addgroup -g ${PGID} -S alpine && \
    adduser -u ${PUID} -G alpine -h /home/alpine -D alpine
RUN set -xe \
    && apk add --no-cache --purge -uU python3 python3-dev \
    && if [[ ! -e /usr/bin/python ]]; then ln -sf $(which python3) /usr/bin/python; fi \
# Install and upgrade Pip
    && python3 -m 'ensurepip' \
    && pip3 install --no-cache --upgrade pip setuptools wheel \
    && if [[ ! -e /usr/bin/pip ]]; then ln -sf $(which pip3) /usr/bin/pip; fi \
    && apk del python3-dev \
    && rm -rf /var/cache/apk/* /tmp/* /usr/lib/python*/ensurepip
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/usr/bin/python"]
